# Generated by Django 4.1.8 on 2023-05-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_alter_auction_current_bid_alter_auction_starting_bid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auction",
            name="image",
        ),
        migrations.AddField(
            model_name="auction",
            name="category",
            field=models.CharField(
                choices=[
                    ("No Category", "No Category"),
                    ("Electronics", "Electronics"),
                    ("Clothing", "Clothing"),
                    ("Home & Garden", "Home & Garden"),
                    ("Toys & Hobbies", "Toys & Hobbies"),
                    ("Automotive", "Automotive"),
                ],
                default="No Category",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="auction",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
